Feat/training request models apis
DeCenter-AI/app.decenterai.com pull request #149
Opened 2023-11-14 11:53 UTC by Sheriff-Oladimeji

### Description

- [x] Resolves 

### Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [x] I have added suitable unit tests (if applicable).

To be reviewed by: @Nasfame @techyNonso

2023-11-14 11:57 UTC, Nasfame requested changes

2023-11-14 11:57 UTC, Nasfame commented on src/app/api/prisma/add_training_request/route.ts
> +    const models = await prisma.model.findMany()
this should be Training Request.many

2023-11-14 11:57 UTC, Nasfame commented on src/app/api/prisma/add_training_request/route.ts
> +    const models = await prisma.model.findMany()
Have u tested these apis with postman or a rest client?

2023-11-14 13:35 UTC, Nasfame requested changes

2023-11-14 13:35 UTC, Nasfame commented on src/app/api/prisma/add_training_request/route.ts
> +    const models = await prisma.trainingRequest.findMany()
its meant to be const trainingRequests =

2023-11-14 13:35 UTC, Nasfame commented
@Sheriff-Oladimeji kindly update ur branch

2023-11-14 18:01 UTC, Nasfame approved these changes
LGTM

2023-11-14 18:01 UTC, Nasfame commented on src/app/api/prisma/add_training_request/route.ts
Not exactly what's required, but its alright.

2023-11-14 20:17 UTC, Nasfame commented on src/app/dashboard/settings/profile/components/EditProfile.tsx
>              Save changes
Explain the change @Sheriff-Oladimeji . Shouldn't u be able to reset the changes?

2023-11-17 12:11 UTC, Nasfame reviewed
@techyNonso kindly review this code

2023-12-04 22:01 UTC, techyNonso approved these changes
Am approving this however , hard coded colors is wrong

2023-12-04 22:17 UTC, merged