Fixes/favicon
DeCenter-AI/app.decenterai.com pull request #43
Opened 2023-10-17 20:35 UTC by Codebox124

## Related Issue(s)

Fixes #
Resolves #
Closes #

## Proposed Changes

[//]: # '[List down the specific changes you have made in this pull request.]'

- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [ ] I have added suitable unit tests (if applicable).

## Screenshots

## To-Do

- [ ]

## Additional Information

2023-10-20 15:07 UTC, techyNonso requested changes
@Nasfame  please lookn into this builld error, it is outside the scope of @Codebox124 task. It has to do with prisma.
Also look at file conflicts

2023-10-21 00:05 UTC, Nasfame reviewed
lgtm

2023-10-21 00:06 UTC, Nasfame commented
Resolves #39

2023-10-21 00:08 UTC, Nasfame commented
@Codebox124 still not fixed : https://realfavicongenerator.net/favicon_checker?protocol=https&site=app-decenterai-com-git-fixes-favicon-decenter-ai.vercel.app

2023-10-21 10:09 UTC, Nasfame commented
@Codebox124 update the pr

2023-10-21 10:09 UTC, Nasfame commented
there are unwanted changes, I guess

2023-10-21 20:10 UTC, Nasfame reviewed
...

2023-10-21 20:10 UTC, Nasfame commented on src/app/dashboard/repository/[id]/components/modal.tsx
> -'use client'
keep the code, leave doc comment stating the issue u were facing

2023-10-21 20:30 UTC, Nasfame approved these changes
LGTM

2023-10-21 20:30 UTC, merged